[general]
bars = 36
bitrate = 8
framerate = 30
sensitivity = 300
lower_cutoff_freq = 20
higher_cutoff_freq = 200
sleep_timer = 0

[input]
method = pipewire
source = auto

[smoothing]
integral = 80
monstercat = 1
waves = 0
gravity = 120
noise_reduction = 0.1

[output]
method = raw
data_format = ascii
ascii_max_range = 100
show_idle_bar_height = 0
bar_delimiter = ;
